### ISSUE TITLE
Players data column details

### ISSUE THREAD

**Issue by TaariqKarim** [ewenme/fplr#4]
Hi there,

This is not really a technical issue so I'm not sure if this is the right place to ask this. 

Thank you for this. It works great! I just have a few questions about the players data.

Where can I find explanations for columns in the players data frame. For example, I assume "ep next" is expected points in next game week. How was this calculated?

Also, I'm not sure what is "element type", the difference between "team" and "team code", etc. 

Is there a file that explains this?

Also, will this data frame be updated after every game week?

thanks again

**Comment by ewenme** [comment]
hi! it's not the best place, but I'll try and help out.

> Where can I find explanations for columns in the players data frame. For example, I assume "ep next" is expected points in next game week. How was this calculated?
Also, I'm not sure what is "element type", the difference between "team" and "team code", etc.
Is there a file that explains this?

The data comes directly from FPL (e.g. [https://fantasy.premierleague.com/api/bootstrap-static/](https://fantasy.premierleague.com/api/bootstrap-static/)). Unfortunately, they don't provide documentation (AFAIK). The field names are not altered on my end (to avoid this package breaking if FPL changes stuff). You are welcome to contribute a data dictionary, if you like (I doubt I'll get around to it).

> Also, will this data frame be updated after every game week?

As explained above, most functions call FPL directly. The data frame you see will be the latest FPL data at time of running the function.

Hope that helps :)
